name: Publish release
on:
  release:
    types: [published]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - 
        name: Create env file
        run: |
          touch .env
          echo ORIGIN=${{ secrets.ORIGIN }} >> .env
          echo JWT_SECRET=${{ secrets.JWT_SECRET }} >> .env
          echo COD_API_USER=${{ secrets.COD_API_USER }} >> .env
          echo COD_API_PASS=${{ secrets.COD_API_PASS }} >> .env
          cat .env
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: darrenkeenfanduel/gbnfl-api:latest
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}